---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
  - repo: https://github.com/ansible/ansible-lint.git
    rev: v5.0.6
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
