---
- name: Converge
  hosts: all
  become: true
  vars:
    consul_role: client
    consul_datacenter: "us-east-1"
    consul_encryptkey: "YKbtX0Gc3mnJ7QwaNwNYtg=="
    consul_cert: |
      -----BEGIN CERTIFICATE-----
      MIIDbzCCAlegAwIBAgIBCjANBgkqhkiG9w0BAQUFADBIMQswCQYDVQQGEwJVUzEO
      MAwGA1UECAwFVGV4YXMxDzANBgNVBAcMBkF1c3RpbjEYMBYGA1UECgwPQXVzdGlu
      Q2xvdWRHdXJ1MB4XDTIyMTEyMjE3MTIyMVoXDTMyMTExOTE3MTIyMVowVDEbMBkG
      A1UEAwwSKi5hdXN0aW5jbG91ZC5ndXJ1MQ4wDAYDVQQIDAVUZXhhczELMAkGA1UE
      BhMCVVMxGDAWBgNVBAoMD0F1c3RpbkNsb3VkR3VydTCCASIwDQYJKoZIhvcNAQEB
      BQADggEPADCCAQoCggEBAKiHPmTx6012OVfbDnCN9jwwvf00I5NwLL37bkJTY1PL
      rljIMm8FZIiKsB9HMmWMJ2iHwhOL7ZAKQkhzlHmRhy6YKX/1Ky9pxYyCpVcXCPxR
      d1vGPMQpEVv1YLKAohC/wVod/qDHB2Cs9PwGkMuWpR1oMblkDe7LBiggTnyyezun
      PKTySYgg6/jujAFm7/CTtMB6bFyY72Cf4f6qMLdxji8WqrnPGOIsbKbkUaeWbz1R
      AEhc86oWDjBxJwAj1+n5J6aHVkuqQPLR4xxLBTHYtZhzodvXd4ob+Pvfdpjhe800
      pz+IEe0FtfEqXsa/FoNearUlLi3EwZT6MXOUug7dsjECAwEAAaNYMFYwCQYDVR0T
      BAIwADAdBgNVHQ4EFgQUIvHbsesTu0uEUG8y5AlSTSmzcocwCwYDVR0PBAQDAgWg
      MB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjANBgkqhkiG9w0BAQUFAAOC
      AQEAC3zUxRE+VeaH/NruV2lf7Hykz64KE3r54kfDsNbRAArRqYS4JjsSLSDT8Lvs
      RtRu1EeVDke4z4/Jm1UM5XyUI+N/dXoX377r5qvn+11x6/hkBT269MvN+xIfmGkN
      fnk2URSVjx25aisA/LEi4Z14asUxWotrVqvxwiePnt3VlsDMFSl0se4iTFAWjlKe
      Hs8QIbstq7XdIL3etDsvp1Paf6mR4H60sWIJDHdsPWBXNXET9h+uve2FW8l91YeM
      WffsXoNUy8xjqF+ev3xa9pSpkfmJFbB22Ba2dB3RIrSHpEaPFEkEWR+xmLG/UrHh
      iBU6aMD9YtWluP8gE6E02wBB3Q==
      -----END CERTIFICATE-----
    consul_key: |
      -----BEGIN PRIVATE KEY-----
      MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCohz5k8etNdjlX
      2w5wjfY8ML39NCOTcCy9+25CU2NTy65YyDJvBWSIirAfRzJljCdoh8ITi+2QCkJI
      c5R5kYcumCl/9SsvacWMgqVXFwj8UXdbxjzEKRFb9WCygKIQv8FaHf6gxwdgrPT8
      BpDLlqUdaDG5ZA3uywYoIE58sns7pzyk8kmIIOv47owBZu/wk7TAemxcmO9gn+H+
      qjC3cY4vFqq5zxjiLGym5FGnlm89UQBIXPOqFg4wcScAI9fp+Semh1ZLqkDy0eMc
      SwUx2LWYc6Hb13eKG/j733aY4XvNNKc/iBHtBbXxKl7GvxaDXmq1JS4txMGU+jFz
      lLoO3bIxAgMBAAECggEAeJMyr/Rp/qTsSBBhV2QqXUweUk+AeJdUW6TNcUTKFwTu
      O3UYqFf6YrqfYfGFfCP3ehFPaL6/fEPqwn13KDdXuZ2Ca5tUh3qsrWg3tYS0mBoN
      RKsjhNFBK0L3KR9hVIxtYPV+3Tco7yEvsjVcWVzxy4VltheA5G17fTAIF612/+jw
      RtyqV+PLTCmHctpW0/rEePZYnpaXF1aEkL6hUukhEaEUcGP7Is7k1SWdK7b+kQ6+
      aT1D288FqQDsHy/wAFmotqJ3LRTDGwHlJ1Lt+0KfTNF8JOw/6fBbnWISFndiOYh/
      TSizzFBAsJFIKcLG7U8LbxTxrMiTbl7nMWUu+9FacQKBgQDexmSkrpQ2WMdb0/CO
      gj2W2Sbwogj0MZSfXLCdOQkHngDd71E/T2jJRpYJURAK7l1C+F3ZB/TH8N/QboRq
      0NUVnYCKnzKK5MMQeAIGvtu2J2gD8dQ97Ul6a20l058e6vyn/0ciHyK4LzZqU+8d
      nbbIr+q8n66VUIyVb1V7RxGnPQKBgQDBqbK/OPwII2kmI/xMRHfYKbCVnniav9qT
      ntnT3b4/oVDoBXs8vpbOGSANtFaQNEIHccWhE/4jf0YY6WzlRSisMZ5TQckN4uu4
      tPr+tc/OB2PwTH4Yt4NkJWqPZr0AF0yrHQcTNdg4H3Hu+6vMR6l+/YL8678W6MNt
      a/7n8aIGBQKBgHtbnGtciJG3g10j9PbUw8n+IQPqlc6yjbvZFatZ49gl9BDw7iqC
      jGG4BmjOTHXhHB9zbHQ7ZZ45kZXXPNfxH61Cc+VO1iv3FNTPvz+A/CTXmU9l38MS
      3Dc/uUbS8i+qq5FTWE5as10ON7GVHLlnlcl3MCKWwZPI8K/m4IzNA8d5AoGAPBHP
      B9E9G6kgLFxtHZr/MWV9CGunLRjlS3SyTC0znbkDx3QrzaOwUy0n7BhL4V7UPErl
      6hixc4E+1OtSg6r3+rFJUrnNCymfxCMe13K9ikJwlVCkrDX/40hXzTMo3KZdeZX/
      Y84HyyC1zlLx7uMrh+BKiPj2xLxeIcqlvnwMraECgYEAlm2JzlhWeKJwfmkp9Ogu
      z1EJDpn3v2rtGMwLBYKpvcsrP01hBwbzPmwjBkqU340p63/c9Xvyj7F7dvc2GKOI
      eVldohWIH5fnF3iLwG1VXTMlPOBrCL/MTPaUGbQNMSV4x932zbRlOAgdBSylfMJ8
      2WQpoxX/Y4YsEQLYCttVqEE=
      -----END PRIVATE KEY-----
    ca_cert: |
      -----BEGIN CERTIFICATE-----
      MIIDDDCCAfQCCQDl9o9ECe/+UTANBgkqhkiG9w0BAQsFADBIMQswCQYDVQQGEwJV
      UzEOMAwGA1UECAwFVGV4YXMxDzANBgNVBAcMBkF1c3RpbjEYMBYGA1UECgwPQXVz
      dGluQ2xvdWRHdXJ1MB4XDTIyMTEyMjE3MTIxMVoXDTMyMTExOTE3MTIxMVowSDEL
      MAkGA1UEBhMCVVMxDjAMBgNVBAgMBVRleGFzMQ8wDQYDVQQHDAZBdXN0aW4xGDAW
      BgNVBAoMD0F1c3RpbkNsb3VkR3VydTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
      AQoCggEBAN4dtGelwL35/RDCkDIzD13QxAHHvHWr1jCngk0edWYrjryJX3MAfMwR
      U9vAtTyzZBO2WKHZ+dGlGBICXBpwbJovIeAhRRf1gl81buxzZKzFAvq8bTzEbmLK
      AVjMzBHLhvkoSVurQuCiwryT6E8Eay+IA7au3dh01ydie3A0z9ax8PXwpfYJNBIF
      T+PhCJ4ilpm0v+PuHuad/XM/QsoYbZLVBdyWRjftMJwFhLz0NNRGCvJDi3QgEoww
      NUOch75O3BIQQ58XmQG+wGMaPk6lvTEs4t00UuQpRQF/dXipMjXO6KbSO0QmfcL1
      61cfzx/lPQt2fL6FptUqY675cqG0RTsCAwEAATANBgkqhkiG9w0BAQsFAAOCAQEA
      YIQOk7RXx2HRGzN8FYnPczofuOsmCTCmQ9lPYOKr3GUCZ87La546Tpugv/51Cr1w
      TYTphqMTpnozQrTNpPrj451mKWupxZPY/sAfrAzOA+dLNT6Jw9Vcrtt9m1xMZLrR
      +LFQBw/Unkj0IVauhaqmPHnXldCD6lyq0FNF/f8OtJaZugFa5/hi8yn/Ua6xunmt
      tnf9IJRYHgcVb4M8FahEngKBo4cvgakuAByb3SK2i9jzcHmWP6YhlqQSn88PIWEM
      +UHY0BNaBQhyyEb/T69G+40Yue1+M93FdUqkR4oaMKwgkUBUx+mny7OUb9uI2qJQ
      tTJ7ZpZ+v8Qx1YxvzvF9lQ==
      -----END CERTIFICATE-----
    vault_cert: |
      -----BEGIN CERTIFICATE-----
      MIIGATCCA+mgAwIBAgICEAEwDQYJKoZIhvcNAQELBQAwgZoxCzAJBgNVBAYTAlVT
      MQ4wDAYDVQQIDAVUZXhhczEbMBkGA1UECgwSTWFjbWlsbGFuIExlYXJuaW5nMTEw
      LwYDVQQLDChNYWNtaWxsYW4gTGVhcm5pbmcgQ2VydGlmaWNhdGUgQXV0aG9yaXR5
      MSswKQYDVQQDDCJNYWNtaWxsYW4gTGVhcm5pbmcgSW50ZXJtZWRpYXRlIENBMB4X
      DTE3MTAwNDIyMjg0NFoXDTE5MTAwNDIyMjg0NFoweTELMAkGA1UEBhMCVVMxDjAM
      BgNVBAgMBVRleGFzMQ8wDQYDVQQHDAZBdXN0aW4xGzAZBgNVBAoMEk1hY21pbGxh
      biBMZWFybmluZzEMMAoGA1UECwwDU1JFMR4wHAYDVQQDDBV2YXVsdC5tYWNtaWxs
      YW4uY2xvdWQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCz4uAZlC/W
      I+bufofEY+5GBA8SQX95xRxC2JDJmobcCLMp1kNSEYL0lKEbEKTa6fre9jmdo3p4
      3yGT2IH5gZymTWTCdXJPGGCv91wjt/dtXewmXCf/QpoGfxkFvlZsJ0i6FL3VZDfQ
      nWfnhKY3udU+pFJaIkwZ1j3QwpBpCDK9I7oBoNP60UsL89fkHgJTwqEbcOU9syZF
      uNUF8SMgCMtrUoPa80XZ2vazDILPxPDPaKQmtrA3kGyeRttAylDearJL/wvYIX+G
      9ZdRUVJ7/8ZakyWvW19skKghFEcmHf0+nDygU7ofgG5Dqnav8Nl3QjDcSTZE1Zvt
      NCbz3GGi4WxpAgMBAAGjggFvMIIBazAJBgNVHRMEAjAAMBEGCWCGSAGG+EIBAQQE
      AwIGQDAzBglghkgBhvhCAQ0EJhYkT3BlblNTTCBHZW5lcmF0ZWQgU2VydmVyIENl
      cnRpZmljYXRlMB0GA1UdDgQWBBSv+87V9sra2nH5NgMZyH78BN5mQjCB0QYDVR0j
      BIHJMIHGgBRr0Ny9XNuCDz6qJMyoFMN6tU3XrKGBqaSBpjCBozELMAkGA1UEBhMC
      VVMxDjAMBgNVBAgMBVRleGFzMQ8wDQYDVQQHDAZBdXN0aW4xGzAZBgNVBAoMEk1h
      Y21pbGxhbiBMZWFybmluZzExMC8GA1UECwwoTWFjbWlsbGFuIExlYXJuaW5nIENl
      cnRpZmljYXRlIEF1dGhvcml0eTEjMCEGA1UEAwwaTWFjbWlsbGFuIExlYXJuaW5n
      IFJvb3QgQ0GCAhAAMA4GA1UdDwEB/wQEAwIFoDATBgNVHSUEDDAKBggrBgEFBQcD
      ATANBgkqhkiG9w0BAQsFAAOCAgEAh2h3phGaEWTBtzSzoHZnSNx3/XPK9tpQhVuC
      xIoMr0uhojlbQvEBFQwsNDW+YhmFlnxRZMC8knVM25qGxB/NWnGo1OEZsc+dNn1M
      PYfQL68nsHZssEg//QKxwdb9fP8oS1Nnood6dX0hQnB7djMaP/Sq0goLt0aFyttt
      GLocdADKS8IySxLSvv8zWksBc5tk+LxmfuQV74vk3+ldLe+ehcNFnjoR5r1IZxWy
      t38ezaUcWilejknUehbl/Xh06WVucEDWdx4xsrWL845eDMzify6wEa/fnBQDYXO8
      68uGXQ3wmWZ+hNc81So9MMVv2TsuwfTXPXAfrHDi2liq6ybmrwFbuMY5+gUPlXHY
      Yly0O3tYFugIlaFwSsrplehOcQSLOCQA7Xp6Fvek4TAGFdiTc+8YlFmKG9XYR4uq
      axI7L/yaurA+VB1wj5ElDcRQa4HIJwVycmoh2WtPagF1fmyYltIdgWheWn8FZzQN
      RgRou5A2KGbqNlvDFpvkUYWD7aSocWgL7XLzyurBUwvYtoWOKgeWOMzv/0J4oT+v
      0biTsGXWF+2jIh7Max90rINSG7nPGOl5LuDpexpAKI0dtRzimYtE7tidzaZnkLRH
      te2nKouwG0Y4UEdGLOkLHEVpdILsV4U5z9nuhK9AHUCsiZpr16JRvMUQWnOwYOcP
      8i3G9eI=
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIGITCCBAmgAwIBAgICEAAwDQYJKoZIhvcNAQELBQAwgaMxCzAJBgNVBAYTAlVT
      MQ4wDAYDVQQIDAVUZXhhczEPMA0GA1UEBwwGQXVzdGluMRswGQYDVQQKDBJNYWNt
      aWxsYW4gTGVhcm5pbmcxMTAvBgNVBAsMKE1hY21pbGxhbiBMZWFybmluZyBDZXJ0
      aWZpY2F0ZSBBdXRob3JpdHkxIzAhBgNVBAMMGk1hY21pbGxhbiBMZWFybmluZyBS
      b290IENBMB4XDTE3MTAwNDIyMTUzMFoXDTI3MTAwMjIyMTUzMFowgZoxCzAJBgNV
      BAYTAlVTMQ4wDAYDVQQIDAVUZXhhczEbMBkGA1UECgwSTWFjbWlsbGFuIExlYXJu
      aW5nMTEwLwYDVQQLDChNYWNtaWxsYW4gTGVhcm5pbmcgQ2VydGlmaWNhdGUgQXV0
      aG9yaXR5MSswKQYDVQQDDCJNYWNtaWxsYW4gTGVhcm5pbmcgSW50ZXJtZWRpYXRl
      IENBMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA0fAZ5dlWFyAZg0XU
      5lEXDZ5AuRY9Owd2Wu64ZbhX4fhfQdcGyNjAeS7CLYaKmK1vIJCD1E+dAj8Acv0Y
      0vzxsXg2ZMHZJ0HACviHlvuFWypr+USdBsoqxmwNNIVo7Iz4deurDTqMTTpu93ct
      +1/DKTZJGJ/9KNZabof09gKHQsXAKOpufkkOvfr23Nrs3aTI6//O7h7PBh7bLaRw
      3Zv8YreSR4d559IYTjvXEgdXoGNOvtHv4PFVqRHuapuT05Cj9VNZ6xECsN/8heku
      hSvSeqdkNZO1N2fg4w33tLuolnj5ZprUdnhtlEUNngqMUc/EPGyoM5WSLqCE7Pou
      +Ce0qtGdk5nMboUDqeoZMMDxIpJkNwXzkiEty5IMo4+dbSbX4Ow4SdvlwlE1vIzl
      Qkff731bvIX6ZtceQKBULDVna54+zrO0avVmUwPVcaJdLfXeslJH1N/BFd00b9kB
      2m5dlunk7AXdccC9FVChCjtKvIs7vzUqHZ0B42pkxPEfcFX+jOJ6/jEDOJAECy/C
      uR5A7MluDIOnfmL+NWwbJUzSjQ4hB3tqglD+cfBb60xZmpYaT8TkqYZhqNwNfZs0
      vqUGBXF6baWnbE4ifABYiAq/dTW7hapaF46JnukplNVkBtvtk6LF+jAqvgmomNpf
      b8HT4jof9N5G/vUR6MdxK/9JpeMCAwEAAaNmMGQwHQYDVR0OBBYEFGvQ3L1c24IP
      PqokzKgUw3q1TdesMB8GA1UdIwQYMBaAFBsFIWXvq4NkjbiyD5FbDZsxdgcKMBIG
      A1UdEwEB/wQIMAYBAf8CAQAwDgYDVR0PAQH/BAQDAgGGMA0GCSqGSIb3DQEBCwUA
      A4ICAQBQpiMnuhHBQ0ovi4hRIZ9E2gI7eAk2v/af8UfK7SlmWzJRu5VkwLIJVDlc
      vPzTFmp0wErJroNHSa//QGw6lxq2eFOMOVtgtHZMKa4Ck6arC8ucyGv2/pNWqreU
      GQVSwYbs1aU+tyBYcSm/Kwf5iZKJsCYjaVouUyCfamWcqsDW9ml7xOay8zHxEuyl
      I7NU7eDTx99Upa09nxE9SxmnYFCtfJO7Oah18CaJildFMu//eFGjDA2FeDWxUHTd
      4xrvvia4nxVooRI/r0unlvpiaUQ08oMYlv5S8TPwf9AsEQw6IGecPeN9+iEJO5BO
      p1l0ILzv6YKKn60pah4kqgHX0XVX/aSxQms6Rjaj0A/lw0q8b0z/qHLAzHdo/ozu
      VLZ7J6R2RRI5ojwrdDWro02wvAFjyScyoF+aqyWPWcHW63ITq4jgYxGCHKQzoZzn
      R7KwSJI7ri+PShVOs+BkqDdq7nAqWtAxhjBEvqKTQ08Z5WQiBLPQLABGxQ0K53+Q
      9xQpiJMDSmQQrsIpXMkMbQ0SWAyHC0SqLgZmanq2SeOXbfDJ9VV+CcCj8QdYJn2p
      1SUD8rv4sDOl1cnNXkZU3K0TkyZzuvMLgfw9NsPeAGOLMbb1thdaeNv7oQB/Xfce
      K5I6KkIhqmZFltXlOlCS1RFD3foI2+uhhvpY1NlLnb+Ala0ODw==
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIGLjCCBBagAwIBAgIJAOiF4nw94NCqMA0GCSqGSIb3DQEBCwUAMIGjMQswCQYD
      VQQGEwJVUzEOMAwGA1UECAwFVGV4YXMxDzANBgNVBAcMBkF1c3RpbjEbMBkGA1UE
      CgwSTWFjbWlsbGFuIExlYXJuaW5nMTEwLwYDVQQLDChNYWNtaWxsYW4gTGVhcm5p
      bmcgQ2VydGlmaWNhdGUgQXV0aG9yaXR5MSMwIQYDVQQDDBpNYWNtaWxsYW4gTGVh
      cm5pbmcgUm9vdCBDQTAeFw0xNzEwMDQyMjA5MzhaFw0zNzA5MjkyMjA5MzhaMIGj
      MQswCQYDVQQGEwJVUzEOMAwGA1UECAwFVGV4YXMxDzANBgNVBAcMBkF1c3RpbjEb
      MBkGA1UECgwSTWFjbWlsbGFuIExlYXJuaW5nMTEwLwYDVQQLDChNYWNtaWxsYW4g
      TGVhcm5pbmcgQ2VydGlmaWNhdGUgQXV0aG9yaXR5MSMwIQYDVQQDDBpNYWNtaWxs
      YW4gTGVhcm5pbmcgUm9vdCBDQTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoC
      ggIBALLsahNFlSWZN56lNZMYqY2c9rBUtrUWc2OIAuWj776iGjULhrabfVD7/hhC
      6VmHyxQI0BxsU+eaz0m4LOPiDcZPrmktnJ9sQGIPHGgsPVtYRpMhXo/qfyv3fNWf
      8+d86wS6np3JxUKmyfQlUNMvGC3H/ivmq+bgImdu43atjaBgAoYI02rnVyNZGDMM
      y3nyovy5F+SE93bh+TJDLGu/0+o3d1rXAcDAcAxqXqwgbQT1cMzQ8Ls/BefLL/R+
      Sf9YFmWOAaPK77pwcTL8bShsLLGlcbi3plPzT/tcXPhzUDlsyZWL1oZGUQLxJA4p
      Xb5c+7MkEqa66j5Z6hYAl8HH1CJYbvon6DDDvAh5uZsWTk09kUqwbK8FeBOse1pf
      sU+YtX2k7GWpeuR6Q7nayphFKVI0mJcr6o7t/CS3hXJS2pQ3h2rO30OT0xm8isC1
      Gc8xTAzUCTwho9IIcuoezYlbps+tnS7BI+kxh8xTGGadgKaru6CwcwuhFkBj0oQQ
      ds7wu/VTIizTjUHBaQTztu4ZTYV95Dse0LuXM+7YxM/3AEVbJ8LB0brOOJfiZTQh
      7phik+e6bKprAR7XVkiHXcUwb4BOXxx8z66ryJpUvT4X1WYAuOnOEIbk/iymGPtc
      IVkuEIPV7kxe9sizqyRcSJxl+RCiCZqCQLGrrUK4TyRpkksLAgMBAAGjYzBhMB0G
      A1UdDgQWBBQbBSFl76uDZI24sg+RWw2bMXYHCjAfBgNVHSMEGDAWgBQbBSFl76uD
      ZI24sg+RWw2bMXYHCjAPBgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIBhjAN
      BgkqhkiG9w0BAQsFAAOCAgEAqI4SOgoOmQj2S1vGaN/JHsuBuz+rDaopZkdFOUsm
      iWEUjzTxBNPRAc9C+jeyjd+PpZVvvJU1FPRXdcxcsZ617f8cN9JSWPV6GhNWn7+x
      bV1VJd8I5eBUV22F6wcRPzR31Kgyx80JYF3S/9c/wLnJS9zF8dR2ZXGbJGZI0Clk
      0oZ1HRJqWmG/W3UHxM5BZd9M0m2dm0G0vcP2DADAcgITUYn0DXdYm4zsgzuCUX/I
      P5I9V3xJUvcFCl0VfQh+2mYcpoySIhcJWVdJmUg2mpQVMuvWXNvtszmutcQayX+L
      KgQDPpEwFadJ9ycOJsdbrbHd6STWYTEZORHUkQWulunIat+WiKNP3JyyzLPrODFs
      Pq1STk/dr+xUSXdxq+DHI3DGoQGaOVPaRatgUqZqHVa8hyqcVcNsQx6gNtCe8w1H
      bIoOSW7vrdf/a0LLm+E9g6T81cSmoghEmkexhLBrDfvmF8+SWE11mWBaJSzrLfrs
      r/EjkBZW3I0zuWYffq0jpKJsfh9aWX4It5BNbUf04WJzqJtrYSmuRKR6TDqrZMyd
      hte0EwVv3Yx4n51b9GHspAptBLOBYOPNFjxSuitT/9e3UU9rokHi24WPNmrabNbI
      aGmHR4XrwXzkYMq7sc8/oXZFMM5lf5az0muFTp3q0YKDamB8B5CkAKpxj2UdbCoD
      RNU=
      -----END CERTIFICATE-----
    vault_key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEpQIBAAKCAQEAs+LgGZQv1iPm7n6HxGPuRgQPEkF/ecUcQtiQyZqG3AizKdZD
      UhGC9JShGxCk2un63vY5naN6eN8hk9iB+YGcpk1kwnVyTxhgr/dcI7f3bV3sJlwn
      /0KaBn8ZBb5WbCdIuhS91WQ30J1n54SmN7nVPqRSWiJMGdY90MKQaQgyvSO6AaDT
      +tFLC/PX5B4CU8KhG3DlPbMmRbjVBfEjIAjLa1KD2vNF2dr2swyCz8Twz2ikJraw
      N5BsnkbbQMpQ3mqyS/8L2CF/hvWXUVFSe//GWpMlr1tfbJCoIRRHJh39Ppw8oFO6
      H4BuQ6p2r/DZd0Iw3Ek2RNWb7TQm89xhouFsaQIDAQABAoIBAQCg5+nJN5JqnAav
      gqLy+uhh3LOWgtwCElyrNoicrQrAu093tt7VBDD9kg1h5ktwPidXVSxIY7jjccPZ
      OatZgaSb5VKh1uh+87FY9YyHrsE2JPNdhMWKQQsBkKLTTmSDrcgSGweLX2/FvWb5
      4t/DrQigVeAMG+2ylr8Ig2Elcl3gbBkdRuQg+kWh2X6P2oBeio/SHV6WcwNena5K
      O4/23bf1i+TkKHDz7jvoyg+fyhjkoni1aV+pvuu5EcMBJvoku+b7bSwsxnSrwr0o
      SUaMNwDFrvwOqQ9UBWdaL7HhuVi27Agl/gRaVBDAvP2z2RyecVNESgTpzgCCKYBw
      EZpFAL8BAoGBAOuEXznLsiadaHYuGWIblfKm/e5z8OFefKLkgiPgPaR83cg2eCLg
      kcczY4NBmCWg/o0ip4NIIOmD3o76u5KttCtHi9s1wg+Zx42LGZTCw4NkOP1AC3rc
      nuhKsnz9Dul7UEdGwh4ZjTBAcwbrkzStbU1Nq9pJgErTyHSVtNxyNef5AoGBAMOH
      65xVS75pC8BGqiZyT+vXuO2rss1a3iClSk4UZ6JYUgx1DwgxpkFCTfIAP/zkP6wP
      jYHMRTCaQb7/nB878dLAjUD1THO7yImJ0h5HgRSgOCP0s01ohmLQcDfD0ZItLvu5
      vL6rUQFBggxut6dJyuPLaiWmGEzc1VtsaHAjgyPxAoGBANFP6uXNv/4LpVxq6gpE
      ZAatHT9AcZOKSxDmLzc9QuueQel/Z1Pv6/9zD30G3faLV9ANPX0yrHV8yl6ePfhF
      Qru4MXbYFymQTUbhmhGY6vQqLW/97HX7/4qJYIouyYL+IkHGhB0GLnH0xYYf9cs6
      Wsr6PcKZ0lguUpgyuPO22WvZAoGAb9cY70zijEEtlYdV37PW/wFfJ6LkHQ3yrB2f
      SNXnCTcXh0SVmow7mmxAhUGbWB1+Rf6HZEzg7pHtNUCjnkH9ahz1LsigODqa1ADf
      DK69qHyUYAyhWo+E/pRW+66n+sKZcyakTTNUnDFKH65cofVVdcJuLqa4k45lA2wY
      uLu3USECgYEAg2PIiMrPwLZpDuOODYPnYCuzIctprHCZiNgdPPsXskJwNh+LSxYE
      G382XbV41zqZQTkCOGtSWxa03UrVlFNkrmU3z1pqvDvipbjPpFeNQ65jH48Gv5r7
      7DMu1O5xQK1Z0hNF7Spm2+Y+FIcOR9hRxEYo4a3v+tvHElvawNCjBJg=
      -----END RSA PRIVATE KEY-----
  roles:
    - role: austincloudguru.consul
    - role: austincloudguru.vault
