---
- name: Verify
  hosts: all
  gather_facts: false
  vars:
    vault_service: vault.service
    consul_service: consul.service
  vars_files:
    - "../../defaults/main.yml"
  tasks:
    - name: Get the Groups
      ansible.builtin.getent:
        database: group

    - name: Get the Users
      ansible.builtin.getent:
        database: passwd

    - name: Verify Vault configuration exists
      ansible.builtin.stat:
        path: /etc/vault.d/vault_main.hcl
      register: reg_vault_config

    - name: Verify Vault binary exists
      ansible.builtin.stat:
        path: /var/vault/bin/vault
      register: reg_vault_binary

    - name: Verify Vault Log Directory exists
      ansible.builtin.stat:
        path: /var/log/vault
      register: reg_vault_log

    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Assert Results
      ansible.builtin.assert:
        that:
          - getent_passwd.vault is defined
          - getent_passwd.consul is defined
          - getent_group.vault is defined
          - getent_group.consul is defined
          - reg_vault_config.stat.exists
          - reg_vault_config.stat.exists
          - reg_vault_binary.stat.exists
          - reg_vault_log.stat.exists
          - reg_vault_log.stat.isdir
          - ansible_facts.services["{{ vault_service }}"]["state"] == "running"
          - ansible_facts.services["{{ consul_service }}"]["state"] == "running"
        quiet: true
